version: '3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - D:\Libraries\Documents\Influx\data\influx:/var/lib/influxdb2
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    environment:
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=adminadmin
    volumes:
      - D:\Libraries\Documents\Influx\data\chronograf:/var/lib/chronograf